use crate::analyze::{grade, CommitScore, HistoryReport, Severity};

pub fn format_text(report: &HistoryReport) -> String {
    let g = grade(report.overall_score);
    let mut out = format!("\nHistory Health: {g} ({}/100)\n", report.overall_score);
    out.push_str(&format!(
        "  Message quality:     {:>3}%\n",
        report.score_message_quality as u8
    ));
    out.push_str(&format!(
        "  Atomicity:           {:>3}%\n",
        report.score_atomicity as u8
    ));
    out.push_str(&format!(
        "  Size discipline:     {:>3}%\n",
        report.score_size as u8
    ));
    out.push_str(&format!(
        "  Convention:          {:>3}%\n",
        report.score_convention as u8
    ));
    out.push('\n');

    if report.issues.is_empty() {
        out.push_str("  ✓ No issues found.\n");
        return out;
    }

    out.push_str(&format!("Top issues ({} total):\n", report.issues.len()));
    for issue in &report.issues[..report.issues.len().min(10)] {
        let icon = match issue.severity {
            Severity::Critical => "🔴",
            Severity::Warning => "🟡",
            Severity::Info => "🟢",
        };
        let short = if issue.oid.len() >= 7 {
            &issue.oid[..7]
        } else {
            &issue.oid
        };
        out.push_str(&format!("  {icon} {short} — {}\n", issue.message));
    }
    out
}

pub fn format_json(report: &HistoryReport) -> String {
    serde_json::to_string_pretty(report).unwrap_or_default()
}

pub fn format_markdown(report: &HistoryReport) -> String {
    let g = grade(report.overall_score);
    let badge = match g {
        "A" => "![A](https://img.shields.io/badge/health-A-success)",
        "B" => "![B](https://img.shields.io/badge/health-B-yellow)",
        "C" => "![C](https://img.shields.io/badge/health-C-orange)",
        "D" => "![D](https://img.shields.io/badge/health-D-red)",
        _ => "![F](https://img.shields.io/badge/health-F-critical)",
    };

    let mut out = format!(
        r#"## Git History Report

{badge} **{g}** — {score}/100

| Dimension | Score |
|-----------|-------|
| Message quality | {mq}% |
| Atomicity | {at}% |
| Size discipline | {sz}% |
| Convention | {cv}% |

"#,
        badge = badge,
        g = g,
        score = report.overall_score,
        mq = report.score_message_quality as u8,
        at = report.score_atomicity as u8,
        sz = report.score_size as u8,
        cv = report.score_convention as u8,
    );

    if report.issues.is_empty() {
        out.push_str("✅ **No issues found.**\n");
        return out;
    }

    out.push_str(&format!("### Issues ({} total)\n\n", report.issues.len()));
    out.push_str("| Severity | Commit | Message |\n");
    out.push_str("|----------|--------|--------|\n");

    for issue in &report.issues {
        let severity_badge = match issue.severity {
            Severity::Critical => "🔴 CRITICAL",
            Severity::Warning => "🟡 WARNING",
            Severity::Info => "🟢 INFO",
        };
        let short = if issue.oid.len() >= 7 {
            &issue.oid[..7]
        } else {
            &issue.oid
        };
        out.push_str(&format!(
            "| {} | `{}` | {} |\n",
            severity_badge, short, issue.message
        ));
    }

    out.push_str("\n---\n");
    out.push_str(
        "_Report generated by [git-doctor](https://github.com/Mohameddhiab/git-doctor) — `doctor analyze --format markdown`_\n"
    );
    out
}

pub fn format_per_commit_markdown(scores: &[CommitScore]) -> String {
    let mut out = "### Per-Commit Breakdown\n\n".to_string();
    out.push_str("| Commit | Subject | Files | +/- | Quality | Atomicity | Size | Convention |\n");
    out.push_str("|--------|---------|-------|-----|---------|-----------|------|------------|\n");

    for c in scores {
        let short = if c.oid.len() >= 7 {
            &c.oid[..7]
        } else {
            &c.oid
        };
        let flags = {
            let mut f = Vec::new();
            if c.is_wip {
                f.push("⚠WIP");
            }
            if c.is_vague {
                f.push("⚠vague");
            }
            if c.is_oversized {
                f.push("⚠oversized");
            }
            if c.is_mixed_concern {
                f.push("⚠mixed");
            }
            if f.is_empty() {
                "✓".to_string()
            } else {
                f.join(" ")
            }
        };
        out.push_str(&format!(
            "| `{}` | {} {} | {} | +{}/-{} | {}% | {}% | {}% | {}% |\n",
            short,
            flags,
            c.subject,
            c.files_changed,
            c.insertions,
            c.deletions,
            c.message_quality,
            c.atomicity,
            c.size_discipline,
            c.convention,
        ));
    }
    out
}

pub fn generate_html(report: &HistoryReport) -> String {
    let g = grade(report.overall_score);
    let issues_html: String = report
        .issues
        .iter()
        .map(|i| {
            let color = match i.severity {
                Severity::Critical => "#ef4444",
                Severity::Warning => "#f59e0b",
                Severity::Info => "#22c55e",
            };
            format!(
                "<tr style=\"color:{color}\"><td>{}</td><td>{}</td><td>{}</td></tr>\n",
                match i.severity {
                    Severity::Critical => "CRITICAL",
                    Severity::Warning => "WARNING",
                    Severity::Info => "INFO",
                },
                &i.oid[..i.oid.len().min(7)],
                i.message
            )
        })
        .collect::<Vec<_>>()
        .join("");

    format!(
        r#"<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Git History Report</title>
<style>
body {{ font-family: system-ui, sans-serif; max-width: 800px; margin: 2em auto; padding: 0 1em; }}
h1 {{ color: #333; }}
.grade {{ font-size: 4em; font-weight: bold; }}
.A {{ color: #22c55e; }} .B {{ color: #16a34a; }} .C {{ color: #f59e0b; }}
.D {{ color: #f97316; }} .F {{ color: #ef4444; }}
table {{ width: 100%; border-collapse: collapse; }}
td, th {{ padding: 0.5em; text-align: left; border-bottom: 1px solid #eee; }}
</style></head><body>
<h1>Git History Report</h1>
<div class="grade {g}">{g}</div>
<p>Overall score: {score}/100</p>
<table>
<tr><th>Severity</th><th>Commit</th><th>Issue</th></tr>
{issues}
</table>
</body></html>"#,
        score = report.overall_score,
        g = g,
        issues = issues_html,
    )
}
